"""
Visual catalog of all queue theory formulas for the informational gallery.

This module provides presentation-layer metadata ONLY.
It does NOT duplicate or replace the calculation logic in domain/formulas/.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List


@dataclass(frozen=True)
class FormulaCard:
    """Single formula card for the visual gallery."""
    id: str
    name: str
    category: str
    latex: str
    use: str
    function: str
    independent_vars: List[str]
    dependent_var: str
    description: str
    var_descriptions: Dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class CarouselGroup:
    """A themed group of formula cards shown in one carousel."""
    id: str
    title: str
    cards: List[FormulaCard]


# ── Variable glossary (reusable across cards) ────────────────────────
VAR_GLOSSARY: Dict[str, str] = {
    "λ": "Tasa de llegada",
    "μ": "Tasa de servicio",
    "k": "Número de servidores",
    "n": "Número de clientes en el sistema",
    "ρ": "Factor de ocupación / utilización",
    "P0": "Probabilidad de sistema vacío",
    "Pn": "Probabilidad de exactamente n clientes",
    "Pk": "Probabilidad de esperar (todos los servidores ocupados)",
    "PNE": "Probabilidad de no esperar",
    "L": "Número esperado de clientes en el sistema",
    "Lq": "Número esperado de clientes en cola",
    "Ln": "Número esperado condicionado",
    "W": "Tiempo esperado en el sistema",
    "Wq": "Tiempo esperado en cola",
    "Wn": "Tiempo esperado condicionado",
    "CTE": "Costo unitario del tiempo de espera",
    "CTS": "Costo unitario del tiempo en el sistema",
    "CTSE": "Costo unitario del tiempo de servicio y espera",
    "CS": "Costo del servidor / servicio",
    "CT_TE": "Costo total del tiempo de espera",
    "CT_TS": "Costo total del tiempo en el sistema",
    "CT_TSE": "Costo total del tiempo de servicio y espera",
    "CT_S": "Costo total del servicio / servidor",
    "CT": "Costo total",
    "TT": "Tiempo total",
}


# =====================================================================
# CAROUSEL 1 — Introducción y relaciones generales (3)
# =====================================================================
_CAROUSEL_1_CARDS = [
    FormulaCard(
        id="f01",
        name="Tiempo medio entre llegadas",
        category="Introducción / Generales",
        latex=r"T_{llegadas} = \frac{1}{\lambda}",
        use="Convierte tasa de llegada en tiempo promedio entre arribos.",
        function="Interpretación temporal de λ.",
        independent_vars=["λ"],
        dependent_var="T_llegadas",
        description="Si aumenta λ, disminuye el tiempo medio entre llegadas.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"]},
    ),
    FormulaCard(
        id="f02",
        name="Tiempo medio de servicio",
        category="Introducción / Generales",
        latex=r"T_{servicio} = \frac{1}{\mu}",
        use="Convierte tasa de servicio en tiempo promedio de atención.",
        function="Interpretación temporal de μ.",
        independent_vars=["μ"],
        dependent_var="T_servicio",
        description="Expresa la duración media del servicio.",
        var_descriptions={"μ": VAR_GLOSSARY["μ"]},
    ),
    FormulaCard(
        id="f03",
        name="Relación entre tiempo total y tiempo de espera",
        category="Introducción / Generales",
        latex=r"W = W_q + \frac{1}{\mu}",
        use="Relaciona el tiempo total en sistema con la espera y el servicio.",
        function="Identidad general de tiempos.",
        independent_vars=["Wq", "μ"],
        dependent_var="W",
        description="El tiempo total es espera más atención.",
        var_descriptions={"Wq": VAR_GLOSSARY["Wq"], "μ": VAR_GLOSSARY["μ"]},
    ),
]

# =====================================================================
# CAROUSEL 2 — PICS: estabilidad, ocupación y probabilidad (8)
# =====================================================================
_CAROUSEL_2_CARDS = [
    FormulaCard(
        id="f04",
        name="Condición de estabilidad PICS",
        category="PICS",
        latex=r"\frac{\lambda}{\mu} < 1",
        use="Verificar que el sistema M/M/1 sea estable.",
        function="Criterio previo al cálculo.",
        independent_vars=["λ", "μ"],
        dependent_var="Criterio lógico de estabilidad",
        description="El sistema no debe recibir más de lo que puede atender.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"]},
    ),
    FormulaCard(
        id="f05",
        name="Factor de ocupación PICS",
        category="PICS",
        latex=r"\rho = \frac{\lambda}{\mu}",
        use="Medir la utilización del servidor.",
        function="Nivel de ocupación.",
        independent_vars=["λ", "μ"],
        dependent_var="ρ",
        description="Fracción del tiempo en que el servidor está ocupado.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"]},
    ),
    FormulaCard(
        id="f06",
        name="Probabilidad de sistema vacío",
        category="PICS",
        latex=r"P_0 = 1 - \frac{\lambda}{\mu}",
        use="Calcular la probabilidad de que no haya clientes.",
        function="Ociosidad del sistema.",
        independent_vars=["λ", "μ"],
        dependent_var="P0",
        description="Probabilidad de encontrar el sistema desocupado.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"]},
    ),
    FormulaCard(
        id="f07",
        name="Probabilidad de n clientes en el sistema",
        category="PICS",
        latex=r"P_n = P_0 \left(\frac{\lambda}{\mu}\right)^n",
        use="Calcular la probabilidad exacta de n clientes.",
        function="Distribución de estados.",
        independent_vars=["P0", "λ", "μ", "n"],
        dependent_var="Pn",
        description="Probabilidad de un estado específico.",
        var_descriptions={"P0": VAR_GLOSSARY["P0"], "λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"], "n": VAR_GLOSSARY["n"]},
    ),
    FormulaCard(
        id="f08",
        name="Normalización de probabilidades",
        category="PICS",
        latex=r"\sum_{n=0}^{\infty} P_n = 1",
        use="Verificar consistencia probabilística.",
        function="Cierre de la distribución.",
        independent_vars=["Pn"],
        dependent_var="Igualdad de control",
        description="La suma de todas las probabilidades debe ser uno.",
        var_descriptions={"Pn": VAR_GLOSSARY["Pn"]},
    ),
    FormulaCard(
        id="f09",
        name="Utilización como suma de estados ocupados",
        category="PICS",
        latex=r"\rho = \sum_{n=1}^{\infty} P_n",
        use="Interpretar ocupación como probabilidad de no vacío.",
        function="Identidad probabilística.",
        independent_vars=["Pn"],
        dependent_var="ρ",
        description="Ocupación equivale a la probabilidad de que el sistema no esté vacío.",
        var_descriptions={"Pn": VAR_GLOSSARY["Pn"]},
    ),
    FormulaCard(
        id="f10",
        name="Relación de probabilidad geométrica M/M/1",
        category="PICS",
        latex=r"P_n = (1-\rho)\rho^n",
        use="Forma alternativa de la probabilidad de estado.",
        function="Representación equivalente usando ρ.",
        independent_vars=["ρ", "n"],
        dependent_var="Pn",
        description="Versión compacta de la distribución de estados.",
        var_descriptions={"ρ": VAR_GLOSSARY["ρ"], "n": VAR_GLOSSARY["n"]},
    ),
    FormulaCard(
        id="f11",
        name="Probabilidad de servidor ocupado",
        category="PICS",
        latex=r"P_{ocupado} = 1 - P_0 = \rho",
        use="Expresar la ocupación mediante P0.",
        function="Equivalencia útil de interpretación.",
        independent_vars=["P0", "ρ"],
        dependent_var="P_ocupado",
        description="Muestra que sistema ocupado y ocupación son equivalentes.",
        var_descriptions={"P0": VAR_GLOSSARY["P0"], "ρ": VAR_GLOSSARY["ρ"]},
    ),
]

# =====================================================================
# CAROUSEL 3 — PICS: desempeño e identidades (8)
# =====================================================================
_CAROUSEL_3_CARDS = [
    FormulaCard(
        id="f12",
        name="Número esperado en el sistema",
        category="PICS",
        latex=r"L = \frac{\lambda}{\mu - \lambda}",
        use="Obtener clientes promedio en el sistema.",
        function="Congestión total.",
        independent_vars=["λ", "μ"],
        dependent_var="L",
        description="Incluye clientes en cola y en servicio.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"]},
    ),
    FormulaCard(
        id="f13",
        name="Número esperado en la cola",
        category="PICS",
        latex=r"L_q = \frac{\lambda^2}{\mu(\mu-\lambda)}",
        use="Obtener longitud promedio de la cola.",
        function="Congestión en espera.",
        independent_vars=["λ", "μ"],
        dependent_var="Lq",
        description="No incluye el cliente en servicio.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"]},
    ),
    FormulaCard(
        id="f14",
        name="Número esperado condicionado en cola no vacía",
        category="PICS",
        latex=r"L_n = \frac{\lambda}{\mu - \lambda}",
        use="Promedio condicionado según el material analizado.",
        function="Representación condicionada / auxiliar.",
        independent_vars=["λ", "μ"],
        dependent_var="Ln",
        description="Indicador auxiliar del tamaño condicionado.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"]},
    ),
    FormulaCard(
        id="f15",
        name="Tiempo esperado en el sistema",
        category="PICS",
        latex=r"W = \frac{1}{\mu - \lambda}",
        use="Tiempo promedio total del cliente.",
        function="Permanencia en sistema.",
        independent_vars=["λ", "μ"],
        dependent_var="W",
        description="Incluye espera y servicio.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"]},
    ),
    FormulaCard(
        id="f16",
        name="Tiempo esperado en cola",
        category="PICS",
        latex=r"W_q = \frac{\lambda}{\mu(\mu-\lambda)}",
        use="Tiempo promedio de espera antes del servicio.",
        function="Espera promedio.",
        independent_vars=["λ", "μ"],
        dependent_var="Wq",
        description="Mide demora previa a la atención.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"]},
    ),
    FormulaCard(
        id="f17",
        name="Tiempo esperado condicionado",
        category="PICS",
        latex=r"W_n = \frac{1}{\mu - \lambda}",
        use="Tiempo condicionado según el material.",
        function="Indicador auxiliar / condicionado.",
        independent_vars=["λ", "μ"],
        dependent_var="Wn",
        description="Versión condicionada del tiempo promedio.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"]},
    ),
    FormulaCard(
        id="f18",
        name="Ley de Little para el sistema",
        category="PICS",
        latex=r"L = \lambda W",
        use="Relacionar cantidad y tiempo promedio en el sistema.",
        function="Identidad fundamental.",
        independent_vars=["λ", "W"],
        dependent_var="L",
        description="Base de análisis de colas.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "W": VAR_GLOSSARY["W"]},
    ),
    FormulaCard(
        id="f19",
        name="Ley de Little para la cola",
        category="PICS",
        latex=r"L_q = \lambda W_q",
        use="Relacionar cola promedio y espera promedio.",
        function="Identidad fundamental de la cola.",
        independent_vars=["λ", "Wq"],
        dependent_var="Lq",
        description="Conecta tiempo y número esperado en cola.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "Wq": VAR_GLOSSARY["Wq"]},
    ),
]

# =====================================================================
# CAROUSEL 4 — PICS: promedios y costos (11)
# =====================================================================
_CAROUSEL_4_CARDS = [
    FormulaCard(
        id="f20",
        name="Tiempo condicionado a cola no vacía",
        category="PICS",
        latex=r"W_n = \frac{W_q}{\rho}",
        use="Calcular tiempo esperado condicionado a que exista espera.",
        function="Corrección condicional.",
        independent_vars=["Wq", "ρ"],
        dependent_var="Wn",
        description="Ajusta la espera promedio por la probabilidad de esperar.",
        var_descriptions={"Wq": VAR_GLOSSARY["Wq"], "ρ": VAR_GLOSSARY["ρ"]},
    ),
    FormulaCard(
        id="f21",
        name="Tamaño condicionado de cola no vacía",
        category="PICS",
        latex=r"L_n = \frac{L_q}{\rho}",
        use="Calcular cola esperada condicionada.",
        function="Corrección condicional.",
        independent_vars=["Lq", "ρ"],
        dependent_var="Ln",
        description="Ajusta el tamaño promedio de cola.",
        var_descriptions={"Lq": VAR_GLOSSARY["Lq"], "ρ": VAR_GLOSSARY["ρ"]},
    ),
    FormulaCard(
        id="f22",
        name="Promedio muestral de cola",
        category="PICS",
        latex=r"\bar{x} = \frac{\sum x}{n}",
        use="Estimar promedio empírico de observaciones.",
        function="Apoyo muestral.",
        independent_vars=["observaciones x", "n"],
        dependent_var="Promedio muestral",
        description="Media aritmética simple de observaciones de cola.",
        var_descriptions={"n": "número de observaciones"},
    ),
    FormulaCard(
        id="f23",
        name="Promedio muestral condicionado a valores no cero",
        category="PICS",
        latex=r"\bar{x}_{cond} = \frac{\sum x}{m}",
        use="Estimar promedio empírico excluyendo ceros.",
        function="Apoyo muestral condicionado.",
        independent_vars=["observaciones no cero", "m"],
        dependent_var="Promedio condicionado",
        description="Media de observaciones efectivas de espera/cola.",
        var_descriptions={"m": "cantidad de observaciones no cero"},
    ),
    FormulaCard(
        id="f24",
        name="Costo total del tiempo de espera",
        category="PICS",
        latex=r"CT_{TE} = \lambda \cdot 8 \cdot W_q \cdot CTE",
        use="Monetizar la espera diaria.",
        function="Costo de cola.",
        independent_vars=["λ", "Wq", "CTE"],
        dependent_var="CT_TE",
        description="Costo económico asociado al tiempo de espera.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "Wq": VAR_GLOSSARY["Wq"], "CTE": VAR_GLOSSARY["CTE"]},
    ),
    FormulaCard(
        id="f25",
        name="Costo total del tiempo en el sistema",
        category="PICS",
        latex=r"CT_{TS} = \lambda \cdot 8 \cdot W \cdot CTS",
        use="Monetizar la permanencia total del cliente.",
        function="Costo de tiempo total.",
        independent_vars=["λ", "W", "CTS"],
        dependent_var="CT_TS",
        description="Costo económico del tiempo total en sistema.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "W": VAR_GLOSSARY["W"], "CTS": VAR_GLOSSARY["CTS"]},
    ),
    FormulaCard(
        id="f26",
        name="Costo total del tiempo de servicio y espera",
        category="PICS",
        latex=r"CT_{TSE} = \lambda \cdot 8 \cdot \frac{1}{\mu} \cdot CTSE",
        use="Monetizar el tiempo de atención/servicio con costo unitario.",
        function="Costo del servicio.",
        independent_vars=["λ", "μ", "CTSE"],
        dependent_var="CT_TSE",
        description="Costo derivado del tiempo de servicio.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"], "CTSE": VAR_GLOSSARY["CTSE"]},
    ),
    FormulaCard(
        id="f27",
        name="Costo del servidor",
        category="PICS",
        latex=r"CT_S = CS",
        use="Incorporar costo fijo/diario del servidor.",
        function="Costo operativo base.",
        independent_vars=["CS"],
        dependent_var="CT_S",
        description="Costo asociado al servidor único.",
        var_descriptions={"CS": VAR_GLOSSARY["CS"]},
    ),
    FormulaCard(
        id="f28",
        name="Costo total del sistema",
        category="PICS",
        latex=r"CT = CT_{TE} + CT_{TS} + CT_{TSE} + CT_S",
        use="Consolidar todos los costos del sistema.",
        function="Costo global.",
        independent_vars=["CT_TE", "CT_TS", "CT_TSE", "CT_S"],
        dependent_var="CT",
        description="Suma de costos de espera, permanencia, servicio y servidor.",
        var_descriptions={
            "CT_TE": VAR_GLOSSARY["CT_TE"], "CT_TS": VAR_GLOSSARY["CT_TS"],
            "CT_TSE": VAR_GLOSSARY["CT_TSE"], "CT_S": VAR_GLOSSARY["CT_S"],
        },
    ),
    FormulaCard(
        id="f29",
        name="Tiempo total diario de espera usando Wq",
        category="PICS",
        latex=r"TT = \lambda \cdot 8 \cdot 0.30 \cdot W_q",
        use="Tiempo total diario de espera para una fracción específica de usuarios.",
        function="Estimación acumulada.",
        independent_vars=["λ", "Wq"],
        dependent_var="TT",
        description="Usa 30% del flujo como caso de ejemplo del documento.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "Wq": VAR_GLOSSARY["Wq"]},
    ),
    FormulaCard(
        id="f30",
        name="Tiempo total diario de espera usando ρ y Wn",
        category="PICS",
        latex=r"TT = \lambda \cdot 8 \cdot 0.30 \cdot \rho \cdot W_n",
        use="Expresión alternativa del tiempo total diario.",
        function="Equivalente condicionada.",
        independent_vars=["λ", "ρ", "Wn"],
        dependent_var="TT",
        description="Versión alternativa basada en espera condicionada.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "ρ": VAR_GLOSSARY["ρ"], "Wn": VAR_GLOSSARY["Wn"]},
    ),
]

# =====================================================================
# CAROUSEL 5 — PICM: estabilidad y probabilidades I (8)
# =====================================================================
_CAROUSEL_5_CARDS = [
    FormulaCard(
        id="f31",
        name="Condición de estabilidad PICM",
        category="PICM",
        latex=r"\frac{\lambda}{k\mu} < 1",
        use="Verificar estabilidad del sistema multicanal.",
        function="Criterio previo.",
        independent_vars=["λ", "μ", "k"],
        dependent_var="Criterio lógico de estabilidad",
        description="La demanda no debe exceder la capacidad total.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"], "k": VAR_GLOSSARY["k"]},
    ),
    FormulaCard(
        id="f32",
        name="Probabilidad de sistema vacío en PICM",
        category="PICM",
        latex=r"P_0=\frac{1}{\left[\sum_{n=0}^{k-1}\frac{1}{n!}\left(\frac{\lambda}{\mu}\right)^n\right]+\frac{1}{k!}\left(\frac{\lambda}{\mu}\right)^k\left(\frac{k\mu}{k\mu-\lambda}\right)}",
        use="Calcular la probabilidad de sistema vacío en M/M/k.",
        function="Base de las demás probabilidades.",
        independent_vars=["λ", "μ", "k"],
        dependent_var="P0",
        description="Probabilidad de que no haya clientes ni servidores ocupados.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"], "k": VAR_GLOSSARY["k"]},
    ),
    FormulaCard(
        id="f33",
        name="Probabilidad de esperar",
        category="PICM",
        latex=r"P_k=\frac{1}{k!}\left(\frac{\lambda}{\mu}\right)^k\left(\frac{k\mu}{k\mu-\lambda}\right)P_0",
        use="Calcular la probabilidad de que todos los servidores estén ocupados.",
        function="Probabilidad de espera.",
        independent_vars=["λ", "μ", "k", "P0"],
        dependent_var="Pk",
        description="Probabilidad de que un nuevo cliente tenga que esperar.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"], "k": VAR_GLOSSARY["k"], "P0": VAR_GLOSSARY["P0"]},
    ),
    FormulaCard(
        id="f34",
        name="Probabilidad de no esperar",
        category="PICM",
        latex=r"P_{NE} = 1 - P_k",
        use="Probabilidad de entrar directamente a servicio.",
        function="Nivel de servicio.",
        independent_vars=["Pk"],
        dependent_var="PNE",
        description="Complemento de la probabilidad de espera.",
        var_descriptions={"Pk": VAR_GLOSSARY["Pk"]},
    ),
    FormulaCard(
        id="f35",
        name="Probabilidad de n clientes para estados bajos",
        category="PICM",
        latex=r"P_n = \frac{P_0}{n!}\left(\frac{\lambda}{\mu}\right)^n",
        use="Calcular probabilidad de n clientes cuando n < k.",
        function="Distribución de estados sin cola saturada.",
        independent_vars=["P0", "λ", "μ", "n"],
        dependent_var="Pn",
        description="Probabilidad de estados con ocupación por debajo del límite de servidores.",
        var_descriptions={"P0": VAR_GLOSSARY["P0"], "λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"], "n": VAR_GLOSSARY["n"]},
    ),
    FormulaCard(
        id="f36",
        name="Probabilidad de n clientes para estados con cola",
        category="PICM",
        latex=r"P_n = \frac{1}{k!\,k^{\,n-k}}\left(\frac{\lambda}{\mu}\right)^n P_0",
        use="Calcular probabilidad de estados cuando n ≥ k.",
        function="Distribución en estados con espera.",
        independent_vars=["k", "λ", "μ", "n", "P0"],
        dependent_var="Pn",
        description="Probabilidad de estados con cola formada.",
        var_descriptions={"k": VAR_GLOSSARY["k"], "λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"], "n": VAR_GLOSSARY["n"], "P0": VAR_GLOSSARY["P0"]},
    ),
    FormulaCard(
        id="f37",
        name="Normalización de probabilidades PICM",
        category="PICM",
        latex=r"\sum_{n=0}^{\infty} P_n = 1",
        use="Verificar consistencia de distribución.",
        function="Cierre probabilístico.",
        independent_vars=["Pn"],
        dependent_var="Igualdad de control",
        description="Suma total de probabilidades igual a uno.",
        var_descriptions={"Pn": VAR_GLOSSARY["Pn"]},
    ),
    FormulaCard(
        id="f38",
        name="Descomposición de estados sin cola y con cola",
        category="PICM",
        latex=r"\sum_{n=0}^{\infty}P_n = \sum_{n=0}^{k-1}P_n + \sum_{n=k}^{\infty}P_n",
        use="Separar estados con servidores disponibles y estados con cola.",
        function="Interpretación estructural del sistema.",
        independent_vars=["Pn", "k"],
        dependent_var="Descomposición de control",
        description="División conceptual de la distribución.",
        var_descriptions={"Pn": VAR_GLOSSARY["Pn"], "k": VAR_GLOSSARY["k"]},
    ),
]

# =====================================================================
# CAROUSEL 6 — PICM: probabilidades II y desempeño (8)
# =====================================================================
_CAROUSEL_6_CARDS = [
    FormulaCard(
        id="f39",
        name="Probabilidad total de estados con cola",
        category="PICM",
        latex=r"\sum_{n=k}^{\infty}P_n = P_k",
        use="Interpretar Pk como masa total de estados con espera.",
        function="Equivalencia probabilística.",
        independent_vars=["Pn", "k"],
        dependent_var="Pk",
        description="Suma de estados donde todos los servidores están ocupados.",
        var_descriptions={"Pn": VAR_GLOSSARY["Pn"], "k": VAR_GLOSSARY["k"]},
    ),
    FormulaCard(
        id="f40",
        name="Número esperado en el sistema PICM",
        category="PICM",
        latex=r"L=\frac{\lambda\mu\left(\frac{\lambda}{\mu}\right)^k}{(k-1)!(k\mu-\lambda)^2}P_0+\frac{\lambda}{\mu}",
        use="Obtener clientes promedio en sistema multicanal.",
        function="Congestión total en M/M/k.",
        independent_vars=["λ", "μ", "k", "P0"],
        dependent_var="L",
        description="Incluye clientes atendidos y en cola.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"], "k": VAR_GLOSSARY["k"], "P0": VAR_GLOSSARY["P0"]},
    ),
    FormulaCard(
        id="f41",
        name="Número esperado en cola PICM",
        category="PICM",
        latex=r"L_q=\frac{\lambda\mu\left(\frac{\lambda}{\mu}\right)^k P_0}{(k-1)!(k\mu-\lambda)^2}",
        use="Obtener longitud promedio de la cola en M/M/k.",
        function="Congestión en espera.",
        independent_vars=["λ", "μ", "k", "P0"],
        dependent_var="Lq",
        description="Clientes promedio esperando atención.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"], "k": VAR_GLOSSARY["k"], "P0": VAR_GLOSSARY["P0"]},
    ),
    FormulaCard(
        id="f42",
        name="Longitud condicionada de cola",
        category="PICM",
        latex=r"L_n = \frac{L_q}{P_k}",
        use="Calcular cola esperada condicionada a que exista espera.",
        function="Corrección condicional.",
        independent_vars=["Lq", "Pk"],
        dependent_var="Ln",
        description="Cola promedio en estados con espera.",
        var_descriptions={"Lq": VAR_GLOSSARY["Lq"], "Pk": VAR_GLOSSARY["Pk"]},
    ),
    FormulaCard(
        id="f43",
        name="Tiempo esperado en el sistema PICM",
        category="PICM",
        latex=r"W=\frac{\mu\left(\frac{\lambda}{\mu}\right)^k P_0}{(k-1)!(k\mu-\lambda)^2}+\frac{1}{\mu}",
        use="Calcular permanencia promedio total del cliente.",
        function="Tiempo total en M/M/k.",
        independent_vars=["λ", "μ", "k", "P0"],
        dependent_var="W",
        description="Suma espera y servicio.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"], "k": VAR_GLOSSARY["k"], "P0": VAR_GLOSSARY["P0"]},
    ),
    FormulaCard(
        id="f44",
        name="Tiempo esperado en cola PICM",
        category="PICM",
        latex=r"W_q=\frac{\mu\left(\frac{\lambda}{\mu}\right)^k P_0}{(k-1)!(k\mu-\lambda)^2}",
        use="Calcular demora promedio antes de servicio.",
        function="Espera en M/M/k.",
        independent_vars=["λ", "μ", "k", "P0"],
        dependent_var="Wq",
        description="Tiempo promedio de espera.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"], "k": VAR_GLOSSARY["k"], "P0": VAR_GLOSSARY["P0"]},
    ),
    FormulaCard(
        id="f45",
        name="Tiempo condicionado de espera",
        category="PICM",
        latex=r"W_n = \frac{W_q}{P_k}",
        use="Tiempo esperado condicionado a que el cliente deba esperar.",
        function="Corrección condicional.",
        independent_vars=["Wq", "Pk"],
        dependent_var="Wn",
        description="Espera promedio en estados con cola.",
        var_descriptions={"Wq": VAR_GLOSSARY["Wq"], "Pk": VAR_GLOSSARY["Pk"]},
    ),
    FormulaCard(
        id="f46",
        name="Probabilidad objetivo de no espera",
        category="PICM",
        latex=r"P_{NE} \ge 0.85",
        use="Criterio de diseño para nivel de servicio.",
        function="Meta de calidad.",
        independent_vars=["PNE"],
        dependent_var="Criterio de aceptación",
        description="El sistema debe permitir no esperar al menos en 85% de los casos.",
        var_descriptions={"PNE": VAR_GLOSSARY["PNE"]},
    ),
]

# =====================================================================
# CAROUSEL 7 — PICM: tiempos, costos y criterios de decisión (12)
# =====================================================================
_CAROUSEL_7_CARDS = [
    FormulaCard(
        id="f47",
        name="Criterio equivalente de probabilidad de espera",
        category="PICM",
        latex=r"P_k \le 0.15",
        use="Criterio equivalente a PNE ≥ 0.85.",
        function="Meta de diseño.",
        independent_vars=["Pk"],
        dependent_var="Criterio de aceptación",
        description="La probabilidad de esperar no debe superar 15%.",
        var_descriptions={"Pk": VAR_GLOSSARY["Pk"]},
    ),
    FormulaCard(
        id="f48",
        name="Criterio objetivo sobre tiempo total",
        category="PICM",
        latex=r"W \le 0.20",
        use="Meta de diseño respecto al tiempo total en el sistema.",
        function="Control de servicio.",
        independent_vars=["W"],
        dependent_var="Criterio de aceptación",
        description="Limita el tiempo total permitido.",
        var_descriptions={"W": VAR_GLOSSARY["W"]},
    ),
    FormulaCard(
        id="f49",
        name="Costo total del tiempo de espera PICM",
        category="PICM",
        latex=r"CT_{TE} = \lambda \cdot 8 \cdot W_q \cdot CTE",
        use="Monetizar la espera diaria en sistema multicanal.",
        function="Costo de cola.",
        independent_vars=["λ", "Wq", "CTE"],
        dependent_var="CT_TE",
        description="Costo económico de la espera.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "Wq": VAR_GLOSSARY["Wq"], "CTE": VAR_GLOSSARY["CTE"]},
    ),
    FormulaCard(
        id="f50",
        name="Costo total del tiempo en el sistema PICM",
        category="PICM",
        latex=r"CT_{TS} = \lambda \cdot 8 \cdot W \cdot CTS",
        use="Monetizar el tiempo total diario del cliente.",
        function="Costo de permanencia total.",
        independent_vars=["λ", "W", "CTS"],
        dependent_var="CT_TS",
        description="Costo del tiempo de permanencia.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "W": VAR_GLOSSARY["W"], "CTS": VAR_GLOSSARY["CTS"]},
    ),
    FormulaCard(
        id="f51",
        name="Costo total del tiempo de servicio y espera PICM",
        category="PICM",
        latex=r"CT_{TSE} = \lambda \cdot 8 \cdot \frac{1}{\mu} \cdot CTSE",
        use="Monetizar tiempo de servicio con costo unitario.",
        function="Costo del servicio.",
        independent_vars=["λ", "μ", "CTSE"],
        dependent_var="CT_TSE",
        description="Costo asociado al tiempo de servicio.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "μ": VAR_GLOSSARY["μ"], "CTSE": VAR_GLOSSARY["CTSE"]},
    ),
    FormulaCard(
        id="f52",
        name="Costo total de servidores",
        category="PICM",
        latex=r"CT_S = k \cdot CS",
        use="Incorporar costo de múltiples servidores.",
        function="Costo operativo multicanal.",
        independent_vars=["k", "CS"],
        dependent_var="CT_S",
        description="Costo agregado de todos los servidores.",
        var_descriptions={"k": VAR_GLOSSARY["k"], "CS": VAR_GLOSSARY["CS"]},
    ),
    FormulaCard(
        id="f53",
        name="Costo total del sistema PICM",
        category="PICM",
        latex=r"CT = CT_{TE} + CT_{TS} + CT_{TSE} + CT_S",
        use="Consolidar todos los costos del sistema multicanal.",
        function="Costo global del sistema.",
        independent_vars=["CT_TE", "CT_TS", "CT_TSE", "CT_S"],
        dependent_var="CT",
        description="Suma total de costos económicos.",
        var_descriptions={
            "CT_TE": VAR_GLOSSARY["CT_TE"], "CT_TS": VAR_GLOSSARY["CT_TS"],
            "CT_TSE": VAR_GLOSSARY["CT_TSE"], "CT_S": VAR_GLOSSARY["CT_S"],
        },
    ),
    FormulaCard(
        id="f54",
        name="Costo total simplificado",
        category="PICM",
        latex=r"CT = \lambda \cdot 8 \cdot W \cdot CTS + k \cdot CS",
        use="Comparar alternativas en ciertos escenarios simplificados.",
        function="Costo simplificado.",
        independent_vars=["λ", "W", "CTS", "k", "CS"],
        dependent_var="CT",
        description="Versión reducida de costo total.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "W": VAR_GLOSSARY["W"], "CTS": VAR_GLOSSARY["CTS"], "k": VAR_GLOSSARY["k"], "CS": VAR_GLOSSARY["CS"]},
    ),
    FormulaCard(
        id="f55",
        name="Tiempo total diario usando Wq",
        category="PICM",
        latex=r"TT = \lambda \cdot 8 \cdot 0.30 \cdot W_q",
        use="Estimar acumulado diario de espera para una fracción de usuarios.",
        function="Tiempo total acumulado.",
        independent_vars=["λ", "Wq"],
        dependent_var="TT",
        description="Tiempo total basado en espera promedio.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "Wq": VAR_GLOSSARY["Wq"]},
    ),
    FormulaCard(
        id="f56",
        name="Tiempo total diario usando Pk y Wn",
        category="PICM",
        latex=r"TT = \lambda \cdot 8 \cdot 0.30 \cdot P_k \cdot W_n",
        use="Versión alternativa condicionada del tiempo total.",
        function="Equivalente condicionada.",
        independent_vars=["λ", "Pk", "Wn"],
        dependent_var="TT",
        description="Tiempo total usando probabilidad de esperar.",
        var_descriptions={"λ": VAR_GLOSSARY["λ"], "Pk": VAR_GLOSSARY["Pk"], "Wn": VAR_GLOSSARY["Wn"]},
    ),
    FormulaCard(
        id="f57",
        name="Criterio de minimización del costo total",
        category="PICM",
        latex=r"\min(CT)",
        use="Seleccionar la alternativa de menor costo total.",
        function="Optimización económica.",
        independent_vars=["CT"],
        dependent_var="Decisión óptima",
        description="Criterio para comparar configuraciones de servidores.",
        var_descriptions={"CT": VAR_GLOSSARY["CT"]},
    ),
    FormulaCard(
        id="f58",
        name="Meta de probabilidad máxima de espera",
        category="PICM",
        latex=r"P_k \le 0.10",
        use="Criterio de diseño más estricto para ciertas aplicaciones.",
        function="Nivel de servicio objetivo.",
        independent_vars=["Pk"],
        dependent_var="Criterio de aceptación",
        description="La espera no debe exceder 10%.",
        var_descriptions={"Pk": VAR_GLOSSARY["Pk"]},
    ),
]


# ── Public API ──────────────────────────────────────────────────────
GALLERY_CAROUSELS: List[CarouselGroup] = [
    CarouselGroup(id="c1", title="Introducción y relaciones generales", cards=_CAROUSEL_1_CARDS),
    CarouselGroup(id="c2", title="PICS: estabilidad, ocupación y probabilidad", cards=_CAROUSEL_2_CARDS),
    CarouselGroup(id="c3", title="PICS: desempeño e identidades", cards=_CAROUSEL_3_CARDS),
    CarouselGroup(id="c4", title="PICS: promedios y costos", cards=_CAROUSEL_4_CARDS),
    CarouselGroup(id="c5", title="PICM: estabilidad y probabilidades I", cards=_CAROUSEL_5_CARDS),
    CarouselGroup(id="c6", title="PICM: probabilidades II y desempeño", cards=_CAROUSEL_6_CARDS),
    CarouselGroup(id="c7", title="PICM: tiempos, costos y criterios de decisión", cards=_CAROUSEL_7_CARDS),
]

TOTAL_FORMULA_COUNT = sum(len(c.cards) for c in GALLERY_CAROUSELS)
