from __future__ import annotations

from typing import Any

from .definitions import CategoryDefinition, VariableDefinition
from .enums import (
    FormulaCategory,
    FormulaType,
    VariableScope,
    VariableType,
)


VARIABLE_CATALOG: dict[str, VariableDefinition] = {
    "lambda_": VariableDefinition(
        id="lambda_",
        symbol="λ",
        display_name="Tasa de llegada",
        description="Tasa de llegada de clientes al sistema por unidad de tiempo.",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.FLOAT,
        unit="clientes / tiempo",
        allowed_categories=[
            FormulaCategory.GENERAL,
            FormulaCategory.PICS,
            FormulaCategory.PICM,
            FormulaCategory.PFCS,
            FormulaCategory.PFCM,
        ],
        constraints={"min": 0, "strict_positive": True},
    ),
    "mu": VariableDefinition(
        id="mu",
        symbol="μ",
        display_name="Tasa de servicio",
        description="Tasa de servicio del sistema por unidad de tiempo.",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.FLOAT,
        unit="clientes / tiempo",
        allowed_categories=[
            FormulaCategory.GENERAL,
            FormulaCategory.PICS,
            FormulaCategory.PICM,
            FormulaCategory.PFCS,
            FormulaCategory.PFCM,
        ],
        constraints={"min": 0, "strict_positive": True},
    ),
    "k": VariableDefinition(
        id="k",
        symbol="k",
        display_name="Servidores",
        description="Número de servidores en el sistema de colas.",
        scope=VariableScope.CATEGORY,
        variable_type=VariableType.INTEGER,
        unit="servidores",
        allowed_categories=[FormulaCategory.PICM, FormulaCategory.PFCM],
        constraints={"min": 1, "integer": True},
    ),
    "M": VariableDefinition(
        id="M",
        symbol="M",
        display_name="Tamaño de población potencial",
        description="Número total de clientes potenciales en el sistema cerrado.",
        scope=VariableScope.CATEGORY,
        variable_type=VariableType.INTEGER,
        unit="clientes",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 1, "integer": True},
    ),
    "n": VariableDefinition(
        id="n",
        symbol="n",
        display_name="Número de clientes en el sistema",
        description="Número de clientes presentes en el sistema de colas.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.INTEGER,
        unit="clientes",
        allowed_categories=[
            FormulaCategory.GENERAL,
            FormulaCategory.PICS,
            FormulaCategory.PICM,
            FormulaCategory.PFCS,
            FormulaCategory.PFCM,
        ],
        constraints={"min": 0, "integer": True},
    ),
    "rho": VariableDefinition(
        id="rho",
        symbol="ρ",
        display_name="Factor de ocupación",
        description="Proporción entre la tasa de llegada y la capacidad de servicio.",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.FLOAT,
        unit="sin unidad",
        allowed_categories=[
            FormulaCategory.GENERAL,
            FormulaCategory.PICS,
            FormulaCategory.PICM,
            FormulaCategory.PFCS,
            FormulaCategory.PFCM,
        ],
        constraints={"min": 0, "max": 1},
    ),
    "P0": VariableDefinition(
        id="P0",
        symbol="P0",
        display_name="Probabilidad de cero clientes",
        description="Probabilidad de que el sistema esté vacío.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="sin unidad",
        allowed_categories=[
            FormulaCategory.GENERAL,
            FormulaCategory.PICS,
            FormulaCategory.PICM,
            FormulaCategory.PFCS,
            FormulaCategory.PFCM,
        ],
        constraints={"min": 0, "max": 1},
    ),
    "Pn": VariableDefinition(
        id="Pn",
        symbol="Pn",
        display_name="Probabilidad de n clientes",
        description="Probabilidad de que haya exactamente n clientes en el sistema.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="sin unidad",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0, "max": 1},
    ),
    "Pk": VariableDefinition(
        id="Pk",
        symbol="Pk",
        display_name="Probabilidad de k clientes",
        description="Probabilidad de que haya exactamente k clientes en el sistema.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="sin unidad",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0, "max": 1},
    ),
    "PNE": VariableDefinition(
        id="PNE",
        symbol="PNE",
        display_name="Probabilidad de no existencia",
        description="Probabilidad de que el evento buscado no ocurra en el sistema.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="sin unidad",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0, "max": 1},
    ),
    "L": VariableDefinition(
        id="L",
        symbol="L",
        display_name="Clientes en el sistema",
        description="Número promedio de clientes en el sistema.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="clientes",
        allowed_categories=[
            FormulaCategory.GENERAL,
            FormulaCategory.PICS,
            FormulaCategory.PICM,
            FormulaCategory.PFCS,
            FormulaCategory.PFCM,
        ],
        constraints={"min": 0},
    ),
    "Lq": VariableDefinition(
        id="Lq",
        symbol="Lq",
        display_name="Clientes en cola",
        description="Número promedio de clientes en la cola.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="clientes",
        allowed_categories=[
            FormulaCategory.GENERAL,
            FormulaCategory.PICS,
            FormulaCategory.PICM,
            FormulaCategory.PFCS,
            FormulaCategory.PFCM,
        ],
        constraints={"min": 0},
    ),
    "Ln": VariableDefinition(
        id="Ln",
        symbol="Ln",
        display_name="Clientes en sistema condicional",
        description="Número de clientes en el sistema bajo una condición específica de n.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="clientes",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0},
    ),
    "W": VariableDefinition(
        id="W",
        symbol="W",
        display_name="Tiempo en el sistema",
        description="Tiempo promedio que un cliente pasa en el sistema.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="tiempo",
        allowed_categories=[
            FormulaCategory.GENERAL,
            FormulaCategory.PICS,
            FormulaCategory.PICM,
            FormulaCategory.PFCS,
            FormulaCategory.PFCM,
        ],
        constraints={"min": 0},
    ),
    "Wq": VariableDefinition(
        id="Wq",
        symbol="Wq",
        display_name="Tiempo en cola",
        description="Tiempo promedio que un cliente pasa esperando en la cola.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="tiempo",
        allowed_categories=[
            FormulaCategory.GENERAL,
            FormulaCategory.PICS,
            FormulaCategory.PICM,
            FormulaCategory.PFCS,
            FormulaCategory.PFCM,
        ],
        constraints={"min": 0},
    ),
    "Wn": VariableDefinition(
        id="Wn",
        symbol="Wn",
        display_name="Tiempo condicional",
        description="Tiempo promedio en el sistema condicionado a n clientes.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="tiempo",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0},
    ),
    "CTE": VariableDefinition(
        id="CTE",
        symbol="CTE",
        display_name="Costo total de espera",
        description="Costo total asociado al tiempo de espera en el sistema.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="moneda",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0},
    ),
    "CTS": VariableDefinition(
        id="CTS",
        symbol="CTS",
        display_name="Costo total de servicio",
        description="Costo total asociado al tiempo de servicio.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="moneda",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0},
    ),
    "CTSE": VariableDefinition(
        id="CTSE",
        symbol="CTSE",
        display_name="Costo total de servicio y espera",
        description="Costo combinado de servicio y espera.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="moneda",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0},
    ),
    "CS": VariableDefinition(
        id="CS",
        symbol="CS",
        display_name="Costo de servicio",
        description="Costo unitario de un servicio.",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.FLOAT,
        unit="moneda / tiempo",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0},
    ),
    "CT_TE": VariableDefinition(
        id="CT_TE",
        symbol="CT_TE",
        display_name="Costo total de tiempo de espera",
        description="Costo total derivado del tiempo de espera.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="moneda",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0},
    ),
    "CT_TS": VariableDefinition(
        id="CT_TS",
        symbol="CT_TS",
        display_name="Costo total de tiempo de servicio",
        description="Costo total derivado del tiempo de servicio.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="moneda",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0},
    ),
    "CT_TSE": VariableDefinition(
        id="CT_TSE",
        symbol="CT_TSE",
        display_name="Costo total de tiempo de servicio y espera",
        description="Costo total derivado del tiempo combinado de servicio y espera.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="moneda",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0},
    ),
    "CT_S": VariableDefinition(
        id="CT_S",
        symbol="CT_S",
        display_name="Costo total de servicio",
        description="Costo total asociado al servicio prestado.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="moneda",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0},
    ),
    "CT": VariableDefinition(
        id="CT",
        symbol="CT",
        display_name="Costo total",
        description="Costo total general del sistema.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="moneda",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0},
    ),
    "TT": VariableDefinition(
        id="TT",
        symbol="TT",
        display_name="Tiempo total",
        description="Tiempo total asociado al proceso de servicio y espera.",
        scope=VariableScope.RESULT,
        variable_type=VariableType.FLOAT,
        unit="tiempo",
        allowed_categories=[FormulaCategory.GENERAL],
        constraints={"min": 0},
    ),
    # ── Variables for new formula groups ──────────────────────────
    "a": VariableDefinition(
        id="a",
        symbol="a",
        display_name="Intensidad de tráfico",
        description="Razón λ/μ del sistema.",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.FLOAT,
        unit="sin unidad",
        allowed_categories=[FormulaCategory.PICM, FormulaCategory.PFHET],
        constraints={"min": 0},
    ),
    "Pc": VariableDefinition(
        id="Pc",
        symbol="Pc",
        display_name="Probabilidad de c clientes",
        description="Probabilidad de que haya exactamente c clientes en el sistema.",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.FLOAT,
        unit="sin unidad",
        allowed_categories=[FormulaCategory.PICM],
        constraints={"min": 0, "max": 1},
    ),
    "r": VariableDefinition(
        id="r",
        symbol="r",
        display_name="Exceso sobre c",
        description="Número de clientes por encima de c (índice de exceso en cola).",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.INTEGER,
        unit="clientes",
        allowed_categories=[FormulaCategory.PICM],
        constraints={"min": 0, "integer": True},
    ),
    "q": VariableDefinition(
        id="q",
        symbol="q",
        display_name="Clientes esperando",
        description="Número de clientes esperando en cola.",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.INTEGER,
        unit="clientes",
        allowed_categories=[FormulaCategory.PICM],
        constraints={"min": 0, "integer": True},
    ),
    "q1": VariableDefinition(
        id="q1",
        symbol="q₁",
        display_name="Primer índice de cola",
        description="Primer valor de clientes esperando (para probabilidad combinada).",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.INTEGER,
        unit="clientes",
        allowed_categories=[FormulaCategory.PICM],
        constraints={"min": 0, "integer": True},
    ),
    "q2": VariableDefinition(
        id="q2",
        symbol="q₂",
        display_name="Segundo índice de cola",
        description="Segundo valor de clientes esperando (para probabilidad combinada).",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.INTEGER,
        unit="clientes",
        allowed_categories=[FormulaCategory.PICM],
        constraints={"min": 0, "integer": True},
    ),
    "mu1": VariableDefinition(
        id="mu1",
        symbol="μ₁",
        display_name="Tasa de servicio servidor 1",
        description="Tasa de servicio del primer servidor (heterogéneo).",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.FLOAT,
        unit="clientes / tiempo",
        allowed_categories=[FormulaCategory.PFHET],
        constraints={"min": 0, "strict_positive": True},
    ),
    "mu2": VariableDefinition(
        id="mu2",
        symbol="μ₂",
        display_name="Tasa de servicio servidor 2",
        description="Tasa de servicio del segundo servidor (heterogéneo).",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.FLOAT,
        unit="clientes / tiempo",
        allowed_categories=[FormulaCategory.PFHET],
        constraints={"min": 0, "strict_positive": True},
    ),
    "mu_bar": VariableDefinition(
        id="mu_bar",
        symbol="μ̄",
        display_name="Tasa media de servicio",
        description="Promedio de las tasas de servicio heterogéneas.",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.FLOAT,
        unit="clientes / tiempo",
        allowed_categories=[FormulaCategory.PFHET],
        constraints={"min": 0, "strict_positive": True},
    ),
    "P1": VariableDefinition(
        id="P1",
        symbol="P₁",
        display_name="Probabilidad de 1 cliente",
        description="Probabilidad de que haya exactamente un cliente en el sistema.",
        scope=VariableScope.GLOBAL,
        variable_type=VariableType.FLOAT,
        unit="sin unidad",
        allowed_categories=[FormulaCategory.PFHET],
        constraints={"min": 0, "max": 1},
    ),
}

CATEGORY_CATALOG: dict[str, CategoryDefinition] = {
    "INTRO": CategoryDefinition(
        id="INTRO",
        name="Introducción / Generales",
        description="Variables y resultados generales de teoría de colas.",
        independent_variables=["lambda_", "mu", "k", "M", "n", "rho"],
        dependent_variables=[
            "P0",
            "Pn",
            "Pk",
            "PNE",
            "L",
            "Lq",
            "Ln",
            "W",
            "Wq",
            "Wn",
            "CTE",
            "CTS",
            "CTSE",
            "CS",
            "CT_TE",
            "CT_TS",
            "CT_TSE",
            "CT_S",
            "CT",
            "TT",
        ],
        shared_variables=["lambda_", "mu", "rho", "CS"],
    ),
    "PICS": CategoryDefinition(
        id="PICS",
        name="PICS",
        description="Colas de Poisson con un solo servidor y capacidad infinita.",
        independent_variables=["lambda_", "mu"],
        dependent_variables=["P0", "Pn", "L", "Lq", "W", "Wq", "rho"],
        shared_variables=["lambda_", "mu", "rho"],
    ),
    "PICM": CategoryDefinition(
        id="PICM",
        name="PICM",
        description="Colas de Poisson con múltiples servidores y capacidad infinita.",
        independent_variables=["lambda_", "mu", "k"],
        dependent_variables=["P0", "Pn", "L", "Lq", "W", "Wq", "rho"],
        shared_variables=["lambda_", "mu", "k", "rho"],
    ),
    "PFCS": CategoryDefinition(
        id="PFCS",
        name="PFCS",
        description="Colas de Poisson con un solo servidor y capacidad finita.",
        independent_variables=["lambda_", "mu", "M"],
        dependent_variables=["P0", "Pn", "L", "Lq", "W", "Wq", "rho"],
        shared_variables=["lambda_", "mu", "M", "rho"],
    ),
    "PFCM": CategoryDefinition(
        id="PFCM",
        name="PFCM",
        description="Colas de Poisson con múltiples servidores y capacidad finita.",
        independent_variables=["lambda_", "mu", "k", "M"],
        dependent_variables=["P0", "Pn", "L", "Lq", "W", "Wq", "rho"],
        shared_variables=["lambda_", "mu", "k", "M", "rho"],
    ),
    "PFHET": CategoryDefinition(
        id="PFHET",
        name="Pob. Finita Heterogénea",
        description="Modelos de nacimiento-muerte con servidores heterogéneos y población finita.",
        independent_variables=["lambda_", "mu1", "mu2", "M", "n", "k"],
        dependent_variables=["P0", "Pn", "L", "Lq", "W", "Wq"],
        shared_variables=["lambda_", "mu1", "mu2", "M"],
    ),
}


def get_variable_definition(variable_id: str) -> VariableDefinition | None:
    return VARIABLE_CATALOG.get(variable_id)


def get_category_definition(category_id: str) -> CategoryDefinition | None:
    return CATEGORY_CATALOG.get(category_id)


def list_variables_by_category(category_id: str) -> list[VariableDefinition]:
    category = CATEGORY_CATALOG.get(category_id)
    if category is None:
        return []
    return [
        VARIABLE_CATALOG[variable_id]
        for variable_id in category.all_variables()
        if variable_id in VARIABLE_CATALOG
    ]
